---
version: '3'
services:
  girder:
    image: dsarchive/annotation_tracker
    build: ../..
    platform: linux/amd64
    # Set CURRENT_UID to your user id (e.g., `CURRENT_UID=$(id -u):$(id -g)`)
    # so that local file assetstores and logs are owned by yourself.
    # user: ${CURRENT_UID}
    restart: unless-stopped
    # Set DSA_PORT to expose the interface on another port (default 8080).
    ports:
      - "${DSA_PORT:-8080}:8080"
    environment:
      - GIRDER_CONFIG=/conf/girder.local.conf
    volumes:
      # Default assetstore
      - fsdata:/assetstore
      - logs:/logs
      # Change for local files:
      # - ./assetstore:/assetstore
      # - ./logs:/logs
      # Location of girder.local.conf and provision.py; add to use local
      # versions
      # - .:/conf
    depends_on:
      - mongodb
      - memcached
    # This is needed to allow fuse to run inside the container.  fuse is only
    # needed if files are on non-filesystem assetstores or multi-file tile
    # sources are used (like mrxs).
    privileged: true
    # Fuse needs fewer permissions than priviledged mode, such as
    # cap_add:
    #   - SYS_ADMIN
    # security_opt:
    #   - apparmor:unconfined
    # devices:
    #   - /dev/fuse:/dev/fuse
    # but these may vary based on the host
  mongodb:
    image: "mongo:latest"
    # Set CURRENT_UID to your user id (e.g., `CURRENT_UID=$(id -u):$(id -g)`)
    # so that local file database and logs are owned by yourself.
    # user: ${CURRENT_UID}
    restart: unless-stopped
    command: --nojournal
    volumes:
      # Location to store database files
      # Change for local files:
      # - ./db:/data/db
      # - ./logs:/var/log/mongodb
      - dbdata:/data/db
  memcached:
    image: memcached
    command: -m 4096 --max-item-size 8M
    restart: unless-stopped

volumes:
  dbdata:
  fsdata:
  logs:
